d={"a":1,"b":2,"c":3}
print(type(d))
print(d["c"])
d.get("d")
print(d.get("d"))
print(d.keys())
print(d.values())
print(d.items())
d.update({"d":4})
print(d)
d.update({"a":3})
print(d)
print(d.setdefault("d",7))
c=d.copy()
print(c)
d.clear()
print(d)

