#tuple
"""x=(1,2,2,2,5,3,2,1,5)
print(x)
print(x[2:5])
print(x[::-1])
print(len(x))
print(max(x))
print(min(x))
print(sum(x))"""
#set
"""s={}
print(type(s))
s=set()
print(type(s))"""
"""s=set({False,False,1,2,2,4,5,4,(2+5j)})
print(s[0])"""
g=set({1,2,3,True,False})
print(g)
print(type(g))
g.add(4)
print(g)
g.update({4,5,6,7})
print(g)
g.remove(3)
print(g)
g.pop()
print(g)
g.discard(False)
print(g)
g.clear()
print(g)
